name: iquhack
channels:
  - plotly
  - defaults
dependencies:
  - jupyter
  - pip
  - plotly
  - python=3
  - statsmodels
  - pip:
    - kaleido
    - pylatexenc
    - qiskit
    - quantuminspire
    - slack-bolt
    - slack-progress
